# -*- coding: utf-8 -*-
"""Calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOBFCLUaLlDaKQ97_pt6eaZLIuetDBqz
"""

#Calculadora Python

print("\nCalculadora Python") #  Este print informa que o programa é uma calculadora
print("\nAo desejar encerrar a calculadora, digite 'sair'") #  Este print informa como encerrar a calculadora

while True: #  While True ficará aguardando uma expressão após a outra para executar enquanto a resposta não for 'sair'

  expressao = input("\nDigite a expressão:") #  Recebe a expressão a ser calculada

  if expressao.lower() == 'sair': #  if condiciona o encerramento da calculada a palavra 'sair', a função .lower() faz com que todas as letras fiquem em minusculo para que seja exatamente "sair" caso seja digitado "Sair ou SAIR"
                                  #  Se a preferência for que a palavra 'sair' fique em maiúsculo, basta alterar .lower() por .upper()
    print("Calculadora encerrada") #  informa que a calculadora está sendo encerrada
    break #  encerra o ciclo while e para a calculadora

  try: #  try seria "realize este código, caso dê errado, pule para except"
    resultado = eval(expressao) #  Eval transforma a entrada em string para uma conta matemática
    print("Resultado: ", resultado) #  imprime o resultado da operação

  except ZeroDivisionError: #  Em caso de divisão por zero, será enviado a mensagem de erro para tentar novamente
    print("Erro: Divisão por zero. Tente novamente")

  except: #  Em caso de operações ilógicas, como "abc + 2" será exibido a mensagem de "Expressão inválida. Tente novamente"
    print("Expressão inválida. Tente novamente")